import { useEffect, useState } from 'react'
import './App.css'

const navItems = [['/', 'Home'], ['/services', 'Services'], ['/clients', 'Profile'], ['/qualifications', 'Team'], ['/contact', 'Contact']]
const routePaths = [...navItems.map(([href]) => href), '/privacy'].filter((href) => href !== '/')
const siteBase = window.location.pathname.includes('/dawit-') ? '/dawit-' : ''
const routePath = (pathname) => {
  const pathnameWithoutBase = pathname.startsWith(siteBase) ? pathname.slice(siteBase.length) : pathname
  return routePaths.find((route) => pathnameWithoutBase === route || pathnameWithoutBase === `${route}/`) || '/'
}

function CalculatorIntro({ onEnter }) {
  const [display, setDisplay] = useState('0')
  const [stored, setStored] = useState(null)
  const [operator, setOperator] = useState(null)
  const [fresh, setFresh] = useState(true)
  const [awake, setAwake] = useState(false)
  const [entering, setEntering] = useState(false)
  const press = (key) => {
    if (entering) return
    if (/^\d$/.test(key) || key === '.') { setDisplay((value) => (fresh || value === '0' ? key : `${value}${key}`)); setFresh(false); return }
    if (key === 'AC') { setDisplay('0'); setStored(null); setOperator(null); setFresh(true); return }
    if (key === '=') {
      if (operator && stored !== null) { const current = Number(display); const result = operator === '+' ? stored + current : operator === '-' ? stored - current : operator === 'x' ? stored * current : stored / current; setDisplay(String(Number.isFinite(result) ? Math.round(result * 100) / 100 : 0)); setStored(null); setOperator(null); setFresh(true) } else { setAwake(true); setEntering(true); onEnter() }
      return
    }
    if (['+', '-', 'x', '/'].includes(key)) { setStored(Number(display)); setOperator(key); setFresh(true) }
  }
  useEffect(() => { const handleKey = (event) => { const map = { '*': 'x', '/': '/', '+': '+', '-': '-', Enter: '=', '=': '=', Escape: 'AC' }; if (/^\d$/.test(event.key) || event.key === '.' || map[event.key]) { event.preventDefault(); press(map[event.key] || event.key) } }; window.addEventListener('keydown', handleKey); return () => window.removeEventListener('keydown', handleKey) })
  const keys = ['MC', 'MR', 'M-', 'M+', 'AC', '%', '/', '7', '8', '9', 'x', '4', '5', '6', '-', '1', '2', '3', '+', '0', '.', '=']
  return <main className={`intro ${awake ? 'is-awake' : ''}`}><div className="intro-meta"><span>EST. 2018</span><span>PRECISION IN PRACTICE</span></div><section className="calculator-wrap" aria-label="Interactive calculator gateway"><div className="calculator"><div className="calculator-top"><span className="screw" /><span>ACCT-08</span><span className="screw" /></div><div className="display-frame"><div className="display" aria-live="polite"><span className="display-brand">DAWIT THEODROS / AUTHORIZED ACCOUNTANT</span><span className="display-number">{display}<span className="display-cursor" /></span></div></div><div className="key-grid">{keys.map((key) => <button key={key} type="button" aria-label={key === '/' ? 'Divide' : key === 'x' ? 'Multiply' : key === '=' ? 'Enter website' : undefined} className={`calc-key key-${key.replace(/[^a-zA-Z0-9]/g, 'op')}`} onClick={() => press(key)}>{key === '/' ? '÷' : key}</button>)}</div><div className="calculator-label">ELECTRONIC ACCOUNTING MACHINE <span>MADE FOR CLEAR THINKING</span></div></div></section><p className="intro-hint"><span className="hint-dot" /> Press <strong>=</strong> to enter the office</p><div className="intro-mark">DAWIT THEODROS<br /><span>ACCOUNTING FIRM</span></div><div className="zap-field" aria-hidden="true" /></main>
}

function SiteNavigation({ path, basePath, onNavigate }) {
  const [open, setOpen] = useState(false)
  const navigate = (event, href) => { event.preventDefault(); setOpen(false); onNavigate(href) }
  return <header className="site-nav"><a className="wordmark" href={`${basePath}/`} onClick={(event) => navigate(event, '/')}>DAWIT THEODROS <span>/ AF</span></a><button className="menu-toggle" aria-expanded={open} onClick={() => setOpen(!open)}><span /> MENU</button><nav className={open ? 'nav-open' : ''}>{navItems.map(([href, label], index) => <a key={href} className={path === href ? 'active' : ''} href={`${basePath}${href}`} onClick={(event) => navigate(event, href)}><small>0{index + 1}</small>{label}</a>)}</nav></header>
}

function PrivacyPage() {
  return <section className="privacy-page"><p className="eyebrow">PRIVACY / 06</p><h1>Your information,<br /><em>handled carefully.</em></h1><p className="lede">Dawit Theodros Accounting Firm uses information shared through this website only to respond to enquiries and provide requested professional services. We do not sell personal information.</p><p className="lede">Contact us at <a href="mailto:contact@dawittheodros.com">contact@dawittheodros.com</a> if you have questions about how your information is handled.</p></section>
}

const pageData = {
  '/services': { eyebrow: 'CAPABILITIES / 02', title: 'More than\nnumbers.', intro: 'Clear financial planning, reporting, compliance, risk management, and leadership for better decisions.', sections: [['01', 'Financial planning & analysis', 'Comprehensive multi-year forecasting, scenario modeling, variance tracking, and capital allocation frameworks designed to safeguard liquidity and scale business operations efficiently.'], ['02', 'Financial reporting & compliance', 'Full-scope balance sheet, P&L, and cash flow statement preparation aligned with IFRS and local regulatory requirements, including complete audit management and tax compliance.'], ['03', 'Strategic financial management & risk', 'Proactive working capital management, currency and credit risk mitigation strategies, and cost-control systems tailored to increase operating margins.'], ['04', 'Operational & team leadership', 'Hands-on management of AP/AR, payroll workflow optimization, internal controls setup, and financial mentorship for department leads.']] },
  '/clients': { eyebrow: 'THE FIRM / 03', title: 'A clear record\nof purpose.', intro: 'Dawit Theodros Accounting Firm is a professional service firm registered in Ethiopia and established in 2018 by Ato Dawit Theodros.', sections: [['VISION', 'A trusted financial partner', 'To support sound decisions through dependable accounting and practical financial insight.'], ['MISSION', 'Professional clarity', 'To provide accurate accounting works, financial statement preparation, tax consulting, finance consulting, and IFRS conversion.'], ['CORE VALUES', 'Precision with integrity', 'Accuracy, confidentiality, accountability, and service-minded guidance shape every engagement.'], ['EXPERIENCE', '8+ years of professional excellence', 'Established in 2018 GC, the firm brings eight years of focused accounting practice to every engagement.'], ['AUTHORISATION', 'Authorized accountant', 'Led by Ato Dawit Theodros with professional service rooted in the Ethiopian business context.']] },
  '/qualifications': { eyebrow: 'THE TEAM / 04', title: 'Experience\nbehind the figures.', intro: 'A capable team brings disciplined work and considered advice to every client relationship.', sections: [['TEAM', 'Full-time and part-time employees', 'The firm works with both full-time and part-time employees to meet the needs of each engagement.'], ['EXPERTISE', 'Master’s-level professionals', 'Many employees hold Master’s degrees in their respective fields.'], ['PRACTICE', '10+ years in their fields', 'Many team members bring more than 10 years of experience in their respective fields.'], ['APPROACH', 'Guidance that stays practical', 'Training, mentoring, and performance goals support consistent quality across finance and accounting work.']] },
}

function HomePage({ onNavigate }) { return <><section className="hero-page"><div className="hero-copy"><p className="eyebrow">ACCOUNTING <i /> TAX <i /> FINANCE</p><h1>Your Trusted<br /><em>Financial Partner.</em></h1><p className="lede">Dawit Theodros Accounting Firm brings 25 years of accounting experience and clear financial insight to every decision.</p><div className="hero-actions"><button className="button button-primary" onClick={() => onNavigate('/services')}>Explore services <span>↗</span></button><button className="text-button" onClick={() => onNavigate('/contact')}>Start a conversation <span>→</span></button></div></div><div className="hero-instrument"><div className="instrument-ring" /><div className="instrument-core"><span>01</span><strong>CLARITY</strong><small>IN EVERY FIGURE</small></div><div className="instrument-line line-one" /><div className="instrument-line line-two" /><span className="hero-coordinate">ETHIOPIA<br />EST. 2018</span></div></section><section className="home-strip"><div><span className="strip-number">01</span><strong>Measured work.<br />Meaningful insight.</strong></div><p>Authorized accounting, practical advice, and dependable reporting for the work that comes next.</p><span className="strip-code">DT / FIELD NOTE 001</span></section></> }

function DetailPage({ data, path }) {
  const [activeItem, setActiveItem] = useState(null)
    return <section className="detail-page"><div className="detail-heading"><p className="eyebrow">{data.eyebrow}</p><h1>{data.title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h1><p className="lede">{data.intro}</p></div>{path === '/clients' && <div className="firm-aside"><div className="experience-mark"><strong>8+</strong><span>YEARS OF<br />PROFESSIONAL<br />EXCELLENCE<br /><i>EST. 2018 GC</i></span></div><div className="partners"><p className="eyebrow">PARTNERS &amp; CLIENTS / 04</p><div className="partner-names"><span>Ever Grand Industries PLC</span><span>Zenith Gebs Eshet Ethiopia</span><span>Alem Business Center</span><small>2000–2008</small></div></div></div>}<div className={`detail-grid ${path === '/clients' ? 'profile-grid' : ''}`}>{data.sections.map(([number, title, description]) => <article className={`detail-item ${activeItem === title ? 'is-open' : ''}`} key={title}><span className="item-number">{number}</span><div><h2>{title}</h2><p>{description}</p></div><button className="item-arrow" type="button" aria-label={`Show details for ${title}`} aria-expanded={activeItem === title} onClick={() => setActiveItem(activeItem === title ? null : title)} onMouseEnter={() => setActiveItem(title)}>↗</button>{activeItem === title && <div className="service-popover"><button type="button" aria-label="Close explanation" onClick={() => setActiveItem(null)}>×</button><strong>{number} — {title}</strong><p>{description}</p></div>}</article>)}</div></section>
}

function ContactPage() { const [openFaq, setOpenFaq] = useState(null); const faqs = [['What services does the firm provide?', 'The firm provides IFRS reporting, bookkeeping, financial statements, tax compliance, planning and analysis, audit support, closing of books, AP/AR, payroll workflows, internal controls, and financial advisory.'], ['How can I start working with the firm?', 'Call 0911687171 or email contact@dawittheodros.com with a short description of your accounting needs.'], ['Where is the firm established?', 'Dawit Theodros Accounting Firm is established in Ethiopia and has operated since 2018 GC.'], ['Does the firm support audits and compliance?', 'Yes. The firm supports audit coordination, tax compliance, regulatory reporting, and practical internal control work.']]; return <section className="contact-page"><div className="contact-heading"><p className="eyebrow">OPEN CHANNEL / 05</p><h1>Let's make<br /><em>things clear.</em></h1><p className="lede">Clear answers about the firm's accounting practice, contact details, and how to begin.</p><div className="contact-details"><span>FIRM</span><p>Dawit Theodros Accounting Firm<br />Authorized Accountant</p><span>PHONE</span><p><a href="tel:+251911687171">0911687171</a></p><span>EMAIL</span><p><a href="mailto:contact@dawittheodros.com">contact@dawittheodros.com</a></p><span>ESTABLISHED</span><p>2018 GC · Ethiopia</p></div></div><div className="faq-section"><p className="eyebrow">FAQ / 05</p><div className="faq-list">{faqs.map(([question, answer], index) => <article className={`faq-item ${openFaq === index ? 'is-open' : ''}`} key={question}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span><strong>{openFaq === index ? '−' : '+'}</strong></button>{openFaq === index && <p>{answer}</p>}</article>)}</div></div></section> }

function App() {
  const [path, setPath] = useState(() => routePath(window.location.pathname))
  const [entered, setEntered] = useState(() => routePath(window.location.pathname) !== '/')
  useEffect(() => { const handlePop = () => setPath(routePath(window.location.pathname)); window.addEventListener('popstate', handlePop); return () => window.removeEventListener('popstate', handlePop) }, [])
  const navigate = (next) => { window.history.pushState({}, '', `${siteBase}${next}`); setPath(next); window.scrollTo(0, 0) }
  if (!entered) return <CalculatorIntro onEnter={() => { const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches; window.setTimeout(() => setEntered(true), reduced ? 0 : 1100) }} />
  const content = path === '/' ? <HomePage onNavigate={navigate} /> : path === '/contact' ? <ContactPage /> : path === '/privacy' ? <PrivacyPage /> : <DetailPage data={pageData[path] || pageData['/services']} path={path} />
  return <div className="site-shell"><SiteNavigation path={path} basePath={siteBase} onNavigate={navigate} /><main className="site-main">{content}</main><footer><span>© 2026 Dawit Theodros Accounting Firm. All rights reserved.</span><a href={`${siteBase}/privacy`} onClick={(event) => { event.preventDefault(); navigate('/privacy') }}>Privacy Policy</a></footer></div>
}

export default App
